<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {
            DB::table('karyawan')->insert([
                [
                    'npy' => '05000008',
                    'nama_lengkap' => 'Tia Hafriana, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-07-01',
                    'unit_id' => 3,
                    'user_id' => 57,
                    'nomor_telepon' => '081234567890',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000015',
                    'nama_lengkap' => 'Yeni, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-07-01',
                    'unit_id' => 3,
                    'user_id' => 61,
                    'nomor_telepon' => '082198765432',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000018',
                    'nama_lengkap' => 'Siti Nurhalisa, S.H.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-02-01',
                    'unit_id' => 3,
                    'user_id' => 54,
                    'nomor_telepon' => '085712345678',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000032',
                    'nama_lengkap' => 'Yana Arsila, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-07-01',
                    'unit_id' => 3,
                    'user_id' => 60,
                    'nomor_telepon' => '081324681357',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000035',
                    'nama_lengkap' => 'Rasmawati, S.Pd.I.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2014-05-21',
                    'unit_id' => 3,
                    'user_id' => 51,
                    'nomor_telepon' => '081299998888',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000106',
                    'nama_lengkap' => 'Yuyun Rusmita, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-07-01',
                    'unit_id' => 3,
                    'user_id' => 62,
                    'nomor_telepon' => '085267891234',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000107',
                    'nama_lengkap' => 'Rusnahwati',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-09-01',
                    'unit_id' => 3,
                    'user_id' => 53,
                    'nomor_telepon' => '083845678912',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000115',
                    'nama_lengkap' => 'Ardi, S.Pd.Gr.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2014-01-20',
                    'unit_id' => 3,
                    'user_id' => 37,
                    'nomor_telepon' => '081912345678',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000201',
                    'nama_lengkap' => 'Heru Purwanto, S.Pd.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2014-05-21',
                    'unit_id' => 3,
                    'user_id' => 42,
                    'nomor_telepon' => '087854321098',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000205',
                    'nama_lengkap' => 'Rika Dwi Anggraini, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2015-08-31',
                    'unit_id' => 3,
                    'user_id' => 52,
                    'nomor_telepon' => '089623456789',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000311',
                    'nama_lengkap' => 'Mihrah Hasan, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-07-01',
                    'unit_id' => 3,
                    'user_id' => 47,
                    'nomor_telepon' => '085678901234',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000343',
                    'nama_lengkap' => 'Umi Kalsum, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2013-07-01',
                    'unit_id' => 3,
                    'user_id' => 45,
                    'nomor_telepon' => '081111112222',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000344',
                    'nama_lengkap' => 'Pandu Riyandi, S.Pd.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2014-05-21',
                    'unit_id' => 3,
                    'user_id' => 49,
                    'nomor_telepon' => '083123456789',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000345',
                    'nama_lengkap' => 'Erik Rahmana, S.Pd.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2015-08-11',
                    'unit_id' => 3,
                    'user_id' => 40,
                    'nomor_telepon' => '081254329876',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000346',
                    'nama_lengkap' => 'Nur Hidayatullah, S.Pd.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2013-07-01',
                    'unit_id' => 3,
                    'user_id' => 48,
                    'nomor_telepon' => '082313578642',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000347',
                    'nama_lengkap' => 'Sutrisno, S.Pd.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2015-05-21',
                    'unit_id' => 3,
                    'user_id' => 56,
                    'nomor_telepon' => '089567894321',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000348',
                    'nama_lengkap' => 'Siti Amalia Hidayah, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2014-05-21',
                    'unit_id' => 3,
                    'user_id' => 55,
                    'nomor_telepon' => '085123456789',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000349',
                    'nama_lengkap' => 'Ana Khairunnisa, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2016-07-14',
                    'unit_id' => 3,
                    'user_id' => 36,
                    'nomor_telepon' => '087776543210',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000350',
                    'nama_lengkap' => 'Juli Elmariza, S.Si.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2016-07-14',
                    'unit_id' => 3,
                    'user_id' => 44,
                    'nomor_telepon' => '081287654321',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000352',
                    'nama_lengkap' => 'Wulandari, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2019-09-24',
                    'unit_id' => 3,
                    'user_id' => 59,
                    'nomor_telepon' => '083212345678',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000355',
                    'nama_lengkap' => 'Agus Purwanti, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2019-01-16',
                    'unit_id' => 3,
                    'user_id' => 34,
                    'nomor_telepon' => '082156784321',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000356',
                    'nama_lengkap' => 'Ahmad Awaludin, S.Pd, M.Pd.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2019-01-28',
                    'unit_id' => 3,
                    'user_id' => 35,
                    'nomor_telepon' => '085324681357',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000441',
                    'nama_lengkap' => 'Prettyana, S.Pd.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2023-06-20',
                    'unit_id' => 3,
                    'user_id' => 50,
                    'nomor_telepon' => '081599997777',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000468',
                    'nama_lengkap' => 'Nur Jayanti, A.Md.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2021-08-09',
                    'unit_id' => 3,
                    'user_id' => 64,
                    'nomor_telepon' => '083345671234',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000481',
                    'nama_lengkap' => 'M Yudi, A.Md.',
                    'jenis_kelamin' => 'L',
                    'tanggal_mulai_bekerja' => '2022-01-17',
                    'unit_id' => 3,
                    'user_id' => 46,
                    'nomor_telepon' => '081267892345',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000497',
                    'nama_lengkap' => 'Dian Faqih, S.Pd., Gr.',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2022-07-12',
                    'unit_id' => 3,
                    'user_id' => 38,
                    'nomor_telepon' => '089734567890',
                    'jabatan_id' => 2,
                ],
                [
                    'npy' => '05000551',
                    'nama_lengkap' => 'Faza Andary Qatrunnada, Lc',
                    'jenis_kelamin' => 'P',
                    'tanggal_mulai_bekerja' => '2023-07-04',
                    'unit_id' => 3,
                    'user_id' => 41,
                    'nomor_telepon' => '081754329876',
                    'jabatan_id' => 2,
                ],
            ]);
        }
    }
}
